manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: kot149
      url-base: https://github.com/kot149
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      
    - name: prospector-zmk-module
      remote: carrefinho
      revision: feat/new-status-screens

    - name: zmk-pointing-acceleration
      remote: oleksandrmaslov
      revision: main

    - name: zmk-listeners
      remote: ssbb
      revision: v1
      path: modules/zmk-listeners

    - name: zmk-mouse-gesture
      remote: kot149
      revision: v1
      path: modules/zmk-mouse-gesture
      
  self:
    path: config
